### ISSUE TITLE
Meteor DevShop talk on ArangoDB

### ISSUE THREAD

**Issue by dandv** [mchacki/mchacki.github.io#1]
Hi Michael,

Iv'e just watched your lightning talk and wanted to offer you [the ArangoDB namespace on Atmosphere](https://atmospherejs.com/arangodb) I had reserved a while back. Let me know what your Meteor Developer account name is, and I'll add you.

**Comment by mchacki** [comment]
Hi Dan,

awesome thank you very much.

My Meteor Developer account name is: mchacki

**Comment by dandv** [comment]
Done. Good luck! Hope to see a solid Arango package.

**Comment by ecwyne** [comment]
@mchacki has there been any movement on the ArangoDB driver for Meteor. I'd be interested in helping out if possible
